openapi: 3.0.3
info:
  title: TFSA Limits
  version: 1.0.0
  description: Provides TFSA contribution limits by year.
servers:
  - url: https://tfsa-limits.herokuapp.com

paths:
  /:
    get:
      summary: Returns all limits.
      responses:
        '200':
          description: Limits returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Limit'
  /{year}:
    get:
      summary: Returns the given year's limit.
      parameters:
        - $ref: '#/components/parameters/PathYear'
      responses:
        '200':
          description: Limit returned successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Limit'
        '404':
          description: Limit not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Inserts or updates the given year's limit.
      parameters:
        - $ref: '#/components/parameters/PathYear'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Limit'
      responses:
        '201':
          description: Limit successfully inserted or updated.
        '401':
          $ref: '#/components/responses/Unauthorized'
    delete:
      summary: Deletes the given year's entry.
      parameters:
        - $ref: '#/components/parameters/PathYear'
      responses:
        '204':
          description: Limit successfully deleted.
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  parameters:
    PathYear:
      name: year
      in: path
      description: Year of interest
      required: true
      schema:
        type: integer
      example: 2010
  schemas:
    Limit:
      properties:
        year:
          type: integer
          example: 2010
        amount:
          type: number
          example: 5000.000
    Error:
      properties:
        timestamp:
          type: string
          example: "2020-08-05T13:33:02.023+00:00"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: 'Not Found'
        message:
          type: string
          example: "Limit for year '2001' not found"
        path:
          type: string
          example: '/2001'
  responses:
    Unauthorized:
      description: Unauthorized access.
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'